version: '3.3'

services:
  evolution-api:
    image: attrium/evolution-api:v2.1.1
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - AUTHENTICATION_API_KEY=B8D69066-512E-4161-8C2A-4C2366881234
      - DATABASE_ENABLED=false
      - DEL_INSTANCE=false
    volumes:
      - evolution_store:/evolution/store

volumes:
  evolution_store:
